version: "3.2"

services:
  postgres:
    image: postgres:10.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph
    networks:
      - aleph

  elasticsearch:
    image: ghcr.io/alephdata/aleph-elasticsearch:3bb5dbed97cfdb9955324d11e5c623a5c5bbc410
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - aleph

  redis:
    image: redis:alpine
    command: [ "redis-server", "--save", "3600", "10" ]
    volumes:
      - redis-data:/data
    networks:
      - aleph

  convert-document:
    image: ghcr.io/alephdata/convert-document:3.16.1
    read_only: true
    restart: on-failure
    user: app
    tmpfs: /tmp
    networks:
      - aleph

  ingest-file:
    image: ghcr.io/alephdata/ingest-file:3.16.1
    tmpfs:
      - /tmp:mode=777
    volumes:
      - archive-data:/data
    depends_on:
      - postgres
      - redis
      - convert-document
    restart: on-failure
    env_file:
      - aleph.env
    networks:
      - aleph

  worker:
    image: alephdata/aleph:${ALEPH_TAG:-3.12.1}
    command: aleph worker
    restart: on-failure
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - ingest-file
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
    env_file:
      - aleph.env
    networks:
      - aleph

  shell:
    image: alephdata/aleph:${ALEPH_TAG:-3.12.1}
    command: /bin/bash
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - ingest-file
      - worker
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
      - "./mappings:/aleph/mappings"
      - "~:/host"
    env_file:
      - aleph.env
    networks:
      - aleph

  api:
    image: alephdata/aleph:${ALEPH_TAG:-3.12.1}
    command: gunicorn -w 6 -b 0.0.0.0:8000 --log-level debug --log-file - aleph.wsgi:app
    expose:
      - 8000
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - worker
      - ingest-file
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
    env_file:
      - aleph.env
    networks:
      - aleph

  ui:
    image: alephdata/aleph-ui-production:${ALEPH_TAG:-3.12.1}
    depends_on:
      - api
    networks:
      - aleph
      - nginx-load-balancer
    #ports:
    #  - "8080:8080"

volumes:
  archive-data: {}
  postgres-data: {}
  redis-data: {}
  elasticsearch-data: {}

networks:
  aleph:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
